/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Solvexa Brand Accents
        'brand-violet': '#8b5cf6',
        'brand-blue': '#3b82f6',
        'brand-cyan': '#06b6d4',
        'brand-neutral': '#0a0a0b',
        // Material Design Token System (from Stitch)
        'primary': '#d0bcff',
        'on-primary': '#3c0091',
        'primary-container': '#a078ff',
        'on-primary-container': '#340080',
        'primary-fixed': '#e9ddff',
        'primary-fixed-dim': '#d0bcff',
        'on-primary-fixed': '#23005c',
        'on-primary-fixed-variant': '#5516be',
        'inverse-primary': '#6d3bd7',
        'secondary': '#adc6ff',
        'on-secondary': '#002e6a',
        'secondary-container': '#0566d9',
        'on-secondary-container': '#e6ecff',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary-fixed': '#001a42',
        'on-secondary-fixed-variant': '#004395',
        'tertiary': '#4cd7f6',
        'on-tertiary': '#003640',
        'tertiary-container': '#009eb9',
        'on-tertiary-container': '#002f38',
        'tertiary-fixed': '#acedff',
        'tertiary-fixed-dim': '#4cd7f6',
        'on-tertiary-fixed': '#001f26',
        'on-tertiary-fixed-variant': '#004e5c',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'surface': '#131314',
        'surface-dim': '#131314',
        'surface-bright': '#3a393a',
        'surface-container-lowest': '#0e0e0f',
        'surface-container-low': '#1c1b1c',
        'surface-container': '#201f20',
        'surface-container-high': '#2a2a2b',
        'surface-container-highest': '#353436',
        'on-surface': '#e5e2e3',
        'on-surface-variant': '#cbc3d7',
        'inverse-surface': '#e5e2e3',
        'inverse-on-surface': '#313031',
        'outline': '#958ea0',
        'outline-variant': '#494454',
        'surface-tint': '#d0bcff',
        'surface-variant': '#353436',
        'background': '#131314',
        'on-background': '#e5e2e3',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'gutter': '20px',
        'margin-mobile': '16px',
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        'sans': ['Inter', 'system-ui', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
        'metadata-sm': ['13px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-lg-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.04em', fontWeight: '800' }],
        'body-md': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'creator-name': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      boxShadow: {
        'signal-glow': '0 0 15px 0 rgba(160, 120, 255, 0.3)',
        'signal-glow-intense': '0 0 25px 0 rgba(160, 120, 255, 0.6)',
        'nav-glow': '0 0 15px rgba(160, 120, 255, 0.15)',
        'cta-glow': '0 4px 20px rgba(160, 120, 255, 0.4)',
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        'marquee': 'marquee 3s linear infinite',
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 15px rgba(160, 120, 255, 0.3)' },
          '50%': { boxShadow: '0 0 25px rgba(160, 120, 255, 0.6)' },
        },
        'marquee': {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
      },
      backdropBlur: {
        'xs': '2px',
        'sm': '4px',
        'DEFAULT': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        '2xl': '24px',
        '3xl': '40px',
      },
      maxWidth: {
        'feed': '680px',
        'content': '1600px',
      },
    },
  },
  plugins: [],
};
